### ISSUE TITLE
Issues around nested routes

### ISSUE THREAD

**Issue by Emily** [lotus/router#42] opened 2015-02-16 19:49 UTC
So Lotus router lets you do this, and doesn't complain:

```ruby
router = Lotus::Router.new do
  resources :groups do
    member do
      resources :activities
    end
  end
end
```

But if we do `puts router.inspector`...

```
/groups/:id/activities GET, HEAD  /groups/:id/activities         /groups/:id/activities::Index
new_/groups/:id/activities GET, HEAD  /groups/:id/activities/new     /groups/:id/activities::New
/groups/:id/activities POST       /groups/:id/activities         /groups/:id/activities::Create
/groups/:id/activities GET, HEAD  /groups/:id/activities/:id     /groups/:id/activities::Show
edit_/groups/:id/activities GET, HEAD  /groups/:id/activities/:id/edit /groups/:id/activities::Edit
/groups/:id/activities PATCH      /groups/:id/activities/:id     /groups/:id/activities::Update
/groups/:id/activities DELETE     /groups/:id/activities/:id     /groups/:id/activities::Destroy
              groups GET, HEAD  /groups                        Groups::Index
          new_groups GET, HEAD  /groups/new                    Groups::New
              groups POST       /groups                        Groups::Create
              groups GET, HEAD  /groups/:id                    Groups::Show
         edit_groups GET, HEAD  /groups/:id/edit               Groups::Edit
              groups PATCH      /groups/:id                    Groups::Update
              groups DELETE     /groups/:id                    Groups::Destroy
```

...it gives us complete nonsense.

Same thing for:

```ruby
router = Lotus::Router.new do
  resources :users do
    member do
      resource :avatar
    end
  end
end
```

```
new_/users/:id/avatar GET, HEAD  /users/:id/avatar/new          /users/:id/avatar::New
   /users/:id/avatar POST       /users/:id/avatar              /users/:id/avatar::Create
   /users/:id/avatar GET, HEAD  /users/:id/avatar              /users/:id/avatar::Show
edit_/users/:id/avatar GET, HEAD  /users/:id/avatar/edit         /users/:id/avatar::Edit
   /users/:id/avatar PATCH      /users/:id/avatar              /users/:id/avatar::Update
   /users/:id/avatar DELETE     /users/:id/avatar              /users/:id/avatar::Destroy
               users GET, HEAD  /users                         Users::Index
           new_users GET, HEAD  /users/new                     Users::New
               users POST       /users                         Users::Create
               users GET, HEAD  /users/:id                     Users::Show
          edit_users GET, HEAD  /users/:id/edit                Users::Edit
               users PATCH      /users/:id                     Users::Update
               users DELETE     /users/:id                     Users::Destroy
```

So from here I see two options:

1. Decide that nested resources are evil, and explicitly disallow them. (And I can totally see arguments for this).
2. Make it work in a more expected manner.

If nested resources were explicitly disallowed, I think there'd be some utility from the `users/:id/avatar` case that would be lost. As such, I think option two is probably the better option.

If option two works, I'd be happy to put together a pull request (though it may take me a while, since it looks like it would be a significant set of changes to the internals here).

**Comment by AlfonsoUceda** [comment] 2015-02-20 14:51
@Emily the first example raises an exception for me:
```
HttpRouter::AmbiguousVariableException: You have duplicate variable names present: id
	from /home/alfonso/.rvm/gems/ruby-2.2.0/gems/http_router-0.11.1/lib/http_router/node/path.rb:10:in `initialize'
	from /home/alfonso/.rvm/gems/ruby-2.2.0/gems/http_router-0.11.1/lib/http_router/node.rb:66:in `new'
	from /home/alfonso/.rvm/gems/ruby-2.2.0/gems/http_router-0.11.1/lib/http_router/node.rb:66:in `add_destination'
	from /home/alfonso/.rvm/gems/ruby-2.2.0/gems/http_router-0.11.1/lib/http_router/node/root.rb:135:in `add_non_path_to_tree'
	from /home/alfonso/.rvm/gems/ruby-2.2.0/gems/http_router-0.11.1/lib/http_router/node/root.rb:84:in `block in add_route'
	from /home/alfonso/.rvm/gems/ruby-2.2.0/gems/http_router-0.11.1/lib/http_router/generator.rb:71:in `block in each_path'
	from /home/alfonso/.rvm/gems/ruby-2.2.0/gems/http_router-0.11.1/lib/http_router/generator.rb:71:in `each'
	from /home/alfonso/.rvm/gems/ruby-2.2.0/gems/http_router-0.11.1/lib/http_router/generator.rb:71:in `each_path'
	from /home/alfonso/.rvm/gems/ruby-2.2.0/gems/http_router-0.11.1/lib/http_router/node/root.rb:72:in `add_route'
	from /home/alfonso/.rvm/gems/ruby-2.2.0/gems/http_router-0.11.1/lib/http_router/node/root.rb:34:in `block in compile'
	from /home/alfonso/.rvm/gems/ruby-2.2.0/gems/http_router-0.11.1/lib/http_router/node/root.rb:34:in `each'
	from /home/alfonso/.rvm/gems/ruby-2.2.0/gems/http_router-0.11.1/lib/http_router/node/root.rb:34:in `compile'
	from /home/alfonso/.rvm/gems/ruby-2.2.0/gems/http_router-0.11.1/lib/http_router.rb:295:in `compile'
	from /home/alfonso/.rvm/gems/ruby-2.2.0/gems/http_router-0.11.1/lib/http_router.rb:238:in `to_s'
	from /home/alfonso/.rvm/gems/ruby-2.2.0/gems/http_router-0.11.1/lib/http_router.rb:243:in `inspect'
	from /home/alfonso/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'

```

**Comment by jodosha** [comment] 2015-03-04 07:57
@Emily Sorry for taking so long to reply. My apologize.

### First example

I can confirm what @AlfonsoUceda said:

```ruby
% bundle console
Resolving dependencies...
irb(main):001:0> router = Lotus::Router.new do
irb(main):002:1*   resources :groups do
irb(main):003:2*     member do
irb(main):004:3*       resources :activities
irb(main):005:3>     end
irb(main):006:2>   end
irb(main):007:1> end
HttpRouter::AmbiguousVariableException: You have duplicate variable names present: id
	from /Users/luca/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router/node/path.rb:10:in `initialize'
	from /Users/luca/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router/node.rb:66:in `new'
	from /Users/luca/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router/node.rb:66:in `add_destination'
	from /Users/luca/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router/node/root.rb:135:in `add_non_path_to_tree'
	from /Users/luca/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router/node/root.rb:84:in `block in add_route'
	from /Users/luca/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router/generator.rb:71:in `block in each_path'
	from /Users/luca/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router/generator.rb:71:in `each'
	from /Users/luca/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router/generator.rb:71:in `each_path'
	from /Users/luca/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router/node/root.rb:72:in `add_route'
	from /Users/luca/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router/node/root.rb:34:in `block in compile'
	from /Users/luca/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router/node/root.rb:34:in `each'
	from /Users/luca/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router/node/root.rb:34:in `compile'
	from /Users/luca/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router.rb:295:in `compile'
	from /Users/luca/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router.rb:238:in `to_s'
	from /Users/luca/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router.rb:243:in `inspect'
	from /Users/luca/.gem/ruby/2.2.0/gems/bundler-1.7.9/lib/bundler/cli/console.rb:38:in `run'
	from /Users/luca/.gem/ruby/2.2.0/gems/bundler-1.7.9/lib/bundler/cli.rb:286:in `console'
	from /Users/luca/.gem/ruby/2.2.0/gems/bundler-1.7.9/lib/bundler/vendor/thor/command.rb:27:in `run'
	from /Users/luca/.gem/ruby/2.2.0/gems/bundler-1.7.9/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
	from /Users/luca/.gem/ruby/2.2.0/gems/bundler-1.7.9/lib/bundler/vendor/thor.rb:363:in `dispatch'
	from /Users/luca/.gem/ruby/2.2.0/gems/bundler-1.7.9/lib/bundler/vendor/thor/base.rb:440:in `start'
	from /Users/luca/.gem/ruby/2.2.0/gems/bundler-1.7.9/lib/bundler/cli.rb:9:in `start'
	from /Users/luca/.gem/ruby/2.2.0/gems/bundler-1.7.9/bin/bundle:20:in `block in <top (required)>'
	from /Users/luca/.gem/ruby/2.2.0/gems/bundler-1.7.9/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
	from /Users/luca/.gem/ruby/2.2.0/gems/bundler-1.7.9/bin/bundle:18:in `<top (required)>'
	from /Users/luca/.gem/ruby/2.2.0/bin/bundle:23:in `load'
	from /Users/luca/.gem/ruby/2.2.0/bin/bundle:23:in `<main>'irb(main):008:0>
```

I'm running that command from my local copy of `lotus-router` repository. My `Gemfile.lock` is:

```
GIT
  remote: git://github.com/lotus/utils.git
  revision: ec6a5d8043395e25cd980ed9bd1b21fb5f0b5178
  branch: 0.3.x
  specs:
    lotus-utils (0.3.4)

PATH
  remote: .
  specs:
    lotus-router (0.2.1)
      http_router (~> 0.11)
      lotus-utils (~> 0.3, >= 0.3.2)

GEM
  remote: https://rubygems.org/
  specs:
    byebug (3.5.1)
      columnize (~> 0.8)
      debugger-linecache (~> 1.2)
      slop (~> 3.6)
    columnize (0.9.0)
    coveralls (0.7.11)
      multi_json (~> 1.10)
      rest-client (>= 1.6.8, < 2)
      simplecov (~> 0.9.1)
      term-ansicolor (~> 1.3)
      thor (~> 0.19.1)
    debugger-linecache (1.2.0)
    docile (1.1.5)
    http_router (0.11.1)
      rack (>= 1.0.0)
      url_mount (~> 0.2.1)
    mime-types (2.4.3)
    minitest (5.5.1)
    multi_json (1.11.0)
    netrc (0.10.3)
    rack (1.6.0)
    rake (10.4.2)
    rest-client (1.7.3)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    simplecov (0.9.2)
      docile (~> 1.1.0)
      multi_json (~> 1.0)
      simplecov-html (~> 0.9.0)
    simplecov-html (0.9.0)
    slop (3.6.0)
    term-ansicolor (1.3.0)
      tins (~> 1.0)
    thor (0.19.1)
    tins (1.3.5)
    url_mount (0.2.1)
      rack
    yard (0.8.7.6)

PLATFORMS
  java
  ruby

DEPENDENCIES
  bundler (~> 1.5)
  byebug
  coveralls
  lotus-router!
  lotus-utils (~> 0.3, >= 0.3.1.dev)!
  minitest (~> 5)
  rake (~> 10)
  simplecov
  yard
```

### Second example

You're right, this is a bug. I'm for keeping nested resources. We can discuss if they are good or not, but those can be required for API endpoints that need that kind of design by specifications.

**Comment by AlfonsoUceda** [comment] 2015-03-09 10:50
In my experience I believe nested routes are useful but only one level, imagine you want get comments by post:
`/post/1/comments/`
For my this is useful but more nested routes are useless, eg:
`granparents/1/parents/1/children`
Can be converted to:
`granparents/1/parents`
`parents/1/children`
because only need the :parent_id to get children

**Comment by jodosha** [comment] 2015-03-20 14:50
@Emily I think I committed I mistake while triaging this issue: the following syntax isn't something that we want to support.

```ruby
member do
  resource :avatar
end
```

This looks like a workaround for nested RESTful resources. I'm closing this, because it isn't a bug, if it doesn't show the right output for unsupported feature.

I think we need proper nested RESTful resources. Opened a ticket for this: https://github.com/lotus/router/issues/47

**Closed by jodosha** 2015-03-20 14:50 UTC
Labels: bug, help-wanted
